export const SET_LIST_PHONG_VE = "SET_LIST_PHONG_VE";

export const DAT_GHE = "DAT_GHE";

export const DAT_GHE_SUCCESS = "DAT_GHE_SUCCESS";

export const CHANGE_STATUS = "CHANGE_STATUS";

export const CHANGE_STATUS_ACTIVE = "CHANGE_STATUS_ACTIVE";

export const CREATE_SHOWTIME_REQUEST = "CREATE_SHOWTIME_REQUEST";
export const CREATE_SHOWTIME_SUCCESS = "CREATE_SHOWTIME_SUCCESS";
export const CREATE_SHOWTIME_FAIL = "CREATE_SHOWTIME_FAIL";

export const RESET_CREATE_SHOWTIME = "RESET_CREATE_SHOWTIME";