export const SET_HE_THONG_RAP_CHIEU = " SET_HE_THONG_RAP_CHIEU";
export const SET_CHI_TIET_PHIM = " SET_CHI_TIET_PHIM";


export const GET_THEATERS_SHOWTIME_REQUEST = "GET_THEATERS_SHOWTIME_REQUEST"; 
export const GET_THEATERS_SHOWTIME_SUCCESS = "GET_THEATERS_SHOWTIME_SUCCESS";
export const GET_THEATERS_SHOWTIME_FAIL = "GET_THEATERS_SHOWTIME_FAIL";
