export const DISPLAY_LOADING = "DISPLAY_LOADING";
export const HIDE_LOADING = "HIDE_LOADING";
export const LOADING_BACKTO_HOME = "LOADING_BACKTO_HOME";
export const LOADING_BACKTO_HOME_COMPLETED = "LOADING_BACKTO_HOME_COMPLETED";
