export const GET_MOVIE_LIST_REQUEST = "GET_MOVIE_LIST_REQUEST";
export const GET_MOVIE_LIST_SUCCESS = "GET_MOVIE_LIST_SUCCESS";
export const GET_MOVIE_LIST_FAIL = "GET_MOVIE_LIST_FAIL";

export const ADD_MOVIE_UPLOAD_REQUEST = "ADD_MOVIE_UPLOAD_REQUEST";
export const ADD_MOVIE_UPLOAD_SUCCESS = "ADD_MOVIE_UPLOAD_SUCCESS";
export const ADD_MOVIE_UPLOAD_FAIL = "ADD_MOVIE_UPLOAD_FAIL";
