export const DANG_NHAP_ACTION = "DANG_NHAP_ACTION";
export const SET_THONG_TIN_NGUOI_DUNG = "SET_THONG_TIN_NGUOI_DUNG";

export const GET_USER_LIST_REQUEST = "GET_USER_LIST_REQUEST";
export const GET_USER_LIST_SUCCESS = "GET_USER_LIST_SUCCESS";
export const GET_USER_LIST_FAIL = "GET_USER_LIST_FAIL";

export const ADD_USER_REQUEST = "ADD_USER_REQUEST";
export const ADD_USER_SUCCESS = "ADD_USER_SUCCESS";
export const ADD_USER_FAIL = "ADD_USER_FAIL";

export const DELETE_USER_REQUEST = "DELETE_USER_REQUEST";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAIL = "DELETE_USER_FAIL";

export const POST_UPDATE_USER_REQUEST = "POST_UPDATE_USER_REQUEST";
export const POST_UPDATE_USER_SUCCESS = "POST_UPDATE_USER_SUCCESS";
export const POST_UPDATE_USER_FAIL = "POST_UPDATE_USER_FAIL";

export const RESET_USER_MANAGEMENT = "RESET_USER_MANAGEMENT";

export const LOGOUT = "LOGOUT";
